version: '3.7'

services:
  scrap_service:
    build: ./scrap_service
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - ./scrap_service/:/app/
    ports:
      - 8501:8000
    networks:
      - front_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrap_service.rule=Host(`scrap.jebzpapy.localhost`)"
      - "traefik.http.routers.scrap_service.entrypoints=web"

  master_service:
    build: ./master_service
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --log-config logger.ini --reload --host 0.0.0.0'
    volumes:
      - ./master_service/:/app/
    ports:
      - 8500:8000
    depends_on:
 #     - scrap_service
      - db
    networks:
      - front_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.master_service.rule=Host(`api.jebzpapy.localhost`)"
      - "traefik.http.routers.master_service.entrypoints=web"

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cenzopapa
      - POSTGRES_PASSWORD=cenzopapa
      - POSTGRES_DB=cenzopapa
    expose:
      - 5432
    networks:
      - front_default

  traefik:
    image: traefik:latest
    ports:
      - "8008:80"
      - "8080:8080"
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - front_default

networks:
  front_default:

volumes:
  postgres_data: