version: '3.3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cenzopapa
      - POSTGRES_PASSWORD=cenzopapa
      - POSTGRES_DB=cenzopapa
    expose:
      - 5432

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: cenzopapa_server
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8001
    restart: always
    expose:
      - 8001
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DEBUG
      - SECRET_KEY
      - REDIS
      - CLOUD_NAME
      - CLOUD_API_KEY
      - CLOUD_API_SECRET
      - SUPER_USER_USERNAME
      - SUPER_USER_EMAIL
      - SUPER_USER_PASS
      - WAIT_HOSTS=db:5432
      - VIRTUAL_HOST=api.jebzpapy.local
      - VIRTUAL_PORT=8001
    depends_on:
      - db
      - redis
  django-q:
    image: cenzopapa_server
    command: python manage.py qcluster
    restart: always
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DEBUG
      - SECRET_KEY
      - REDIS
      - CLOUD_NAME
      - CLOUD_API_KEY
      - CLOUD_API_SECRET
      - SUPER_USER_USERNAME
      - SUPER_USER_EMAIL
      - SUPER_USER_PASS
      - WAIT_HOSTS=db:5432
    depends_on:
      - redis
      - server

volumes:
  postgres_data:

networks:
  default:
    external:
      name: nginx-proxy