version: '3.3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: cenzopapa_server
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8001
    restart: unless-stopped
    expose:
      - 8001
    environment:
      - DB_NAME=cenzopapa
      - DB_USER=cenzopapa
      - DB_PASSWORD=cenzopapa
      - DB_HOST=db
      - DEBUG=1
      - SECRET_KEY=cenzopapa
      - REDIS=redis://redis:6379/1
      - CLOUD_NAME=name
      - CLOUD_API_KEY=key
      - CLOUD_API_SECRET=secret
      - SUPER_USER_USERNAME=username
      - SUPER_USER_EMAIL=email
      - SUPER_USER_PASS=pass
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.jebzpapy.tk`)"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.routers.server.tls.certresolver=letsencrypt"
    networks:
      - cenzopapa
  django-q:
    image: cenzopapa_server
    command: python manage.py qcluster
    restart: unless-stopped
    environment:
      - DB_NAME=cenzopapa
      - DB_USER=cenzopapa
      - DB_PASSWORD=cenzopapa
      - DB_HOST=db
      - DEBUG=1
      - SECRET_KEY=cenzopapa
      - REDIS=redis://redis:6379/1
      - CLOUD_NAME=name
      - CLOUD_API_KEY=key
      - CLOUD_API_SECRET=secret
      - SUPER_USER_USERNAME=username
      - SUPER_USER_EMAIL=email
      - SUPER_USER_PASS=pass
    depends_on:
      - redis
      - server
    networks:
      - cenzopapa
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cenzopapa
      - POSTGRES_PASSWORD=cenzopapa
      - POSTGRES_DB=cenzopapa
    expose:
      - 5432
    networks:
      - cenzopapa
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cenzopapa

  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - cenzopapa
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.jebzpapy.tk`) && (PathPrefix(`/`))"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$3zmpgibf$$LXodktr0JOkTSNAWCZKlw1"

networks:
  cenzopapa:

volumes:
  postgres_data: