version: '3.7'

services:
  master_service:
    build:
      context: ./master_service
      dockerfile: Dockerfile.prod
    ports:
      - 8500:80
    depends_on:
      - scrap_service
      - db
    networks:
      - front_default
  scrap_service:
    build: ./scrap_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./scrap_service/:/app/
    ports:
      - 8501:8000
    networks:
      - front_default

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cenzopapa
      - POSTGRES_PASSWORD=cenzopapa
      - POSTGRES_DB=cenzopapa
    expose:
      - 5432
    networks:
      - front_default

networks:
  front_default:

volumes:
  postgres_data: