# Generated by Django 3.2.9 on 2021-12-01 20:59
import os

from django.db import migrations
from decouple import config


def create_super_user(apps, schema_editor):
    # TODO poprawic na CONFIG
    User = apps.get_model('users', 'CUser')
    password = config("SUPER_USER_PASS")
    username = config("SUPER_USER_USERNAME")
    email = config("SUPER_USER_EMAIL")
    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(username=username, email=email, password=password)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_super_user),
    ]
