# Generated by Django 3.2.9 on 2021-11-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(default='.png', max_length=255)),
                ('remote_image_url', models.URLField(default='http://localhost.pl/image.png')),
                ('public_url', models.URLField(default='https://localhost.pl/image.png')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField()),
                ('height', models.IntegerField(default=600)),
                ('width', models.IntegerField(default=400)),
            ],
        ),
    ]
