# Generated by Django 3.2.9 on 2021-11-11 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
