# Generated by Django 3.2.9 on 2021-11-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
