# Generated by Django 3.2.9 on 2021-11-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20211121_1459'),
        ('images', '0003_image_likes'),
    ]

    operations = [
    ]
