# Generated by Django 3.2.9 on 2021-11-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
