# Generated by Django 3.2.9 on 2021-11-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='remote_image_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='image',
            name='public_url',
        ),
    ]
